// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/analysis/{symbol}": {
            "get": {
                "description": "Get comprehensive fundamental analysis for a specific company. Data collection is automatic if not available.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Analysis"
                ],
                "summary": "Get detailed company analysis",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Company Symbol",
                        "name": "symbol",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/pkg.CompanyAnalysisResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/pkg.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/pkg.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/analysis/{symbol}/valuation": {
            "get": {
                "description": "Get detailed valuation analysis with fair value estimates",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Analysis"
                ],
                "summary": "Get valuation analysis for a company",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Company Symbol",
                        "name": "symbol",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/pkg.ValuationAnalysisResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/pkg.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/pkg.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/collect/{symbol}": {
            "post": {
                "description": "Manually trigger data collection from Alpha Vantage. Note: Data collection is automatic in analysis endpoints.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Data Collection"
                ],
                "summary": "Trigger data collection for a company (Admin/Testing)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Company Symbol",
                        "name": "symbol",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/pkg.SuccessResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/pkg.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/pkg.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/screening": {
            "post": {
                "description": "Filter companies based on valuation, profitability, and financial health criteria",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Screening"
                ],
                "summary": "Screen companies based on fundamental criteria",
                "parameters": [
                    {
                        "description": "Screening criteria",
                        "name": "criteria",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/services.ScreeningCriteria"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/pkg.ScreeningResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/pkg.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/pkg.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/screening/templates": {
            "get": {
                "description": "Get predefined screening templates for common investment strategies",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Screening"
                ],
                "summary": "Get screening templates",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/pkg.ScreeningTemplatesResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "models.AnnualReportIncomeStatements": {
            "type": "object",
            "properties": {
                "comprehensiveIncomeNetOfTax": {
                    "type": "integer"
                },
                "costOfRevenue": {
                    "type": "integer"
                },
                "costofGoodsAndServicesSold": {
                    "type": "integer"
                },
                "depreciation": {
                    "type": "integer"
                },
                "depreciationAndAmortization": {
                    "type": "integer"
                },
                "ebit": {
                    "type": "integer"
                },
                "ebitda": {
                    "type": "integer"
                },
                "fiscalDateEnding": {
                    "type": "string"
                },
                "grossProfit": {
                    "type": "integer"
                },
                "incomeBeforeTax": {
                    "type": "integer"
                },
                "incomeTaxExpense": {
                    "type": "integer"
                },
                "interestAndDebtExpense": {
                    "type": "integer"
                },
                "interestExpense": {
                    "type": "integer"
                },
                "interestIncome": {
                    "type": "integer"
                },
                "investmentIncomeNet": {
                    "description": "Have to handle case where value is \"None\"",
                    "type": "integer"
                },
                "netIncome": {
                    "type": "integer"
                },
                "netIncomeFromContinuingOperations": {
                    "type": "integer"
                },
                "netInterestIncome": {
                    "type": "integer"
                },
                "nonInterestIncome": {
                    "type": "integer"
                },
                "operatingExpenses": {
                    "type": "integer"
                },
                "operatingIncome": {
                    "type": "integer"
                },
                "otherNonOperatingIncome": {
                    "type": "integer"
                },
                "reportedCurrency": {
                    "type": "string"
                },
                "researchAndDevelopment": {
                    "type": "integer"
                },
                "sellingGeneralAndAdministrative": {
                    "type": "integer"
                },
                "totalRevenue": {
                    "type": "integer"
                }
            }
        },
        "models.BalanceSheetAnnualReport": {
            "type": "object",
            "properties": {
                "accumulatedDepreciationAmortizationPPE": {
                    "type": "integer"
                },
                "capitalLeaseObligations": {
                    "type": "integer"
                },
                "cashAndCashEquivalentsAtCarryingValue": {
                    "type": "integer"
                },
                "cashAndShortTermInvestments": {
                    "type": "integer"
                },
                "commonStock": {
                    "type": "integer"
                },
                "commonStockSharesOutstanding": {
                    "type": "integer"
                },
                "currentAccountsPayable": {
                    "type": "integer"
                },
                "currentDebt": {
                    "type": "integer"
                },
                "currentLongTermDebt": {
                    "type": "integer"
                },
                "currentNetReceivables": {
                    "type": "integer"
                },
                "deferredRevenue": {
                    "type": "integer"
                },
                "fiscalDateEnding": {
                    "type": "string"
                },
                "goodwill": {
                    "type": "integer"
                },
                "intangibleAssets": {
                    "type": "integer"
                },
                "intangibleAssetsExcludingGoodwill": {
                    "type": "integer"
                },
                "inventory": {
                    "type": "integer"
                },
                "investments": {
                    "type": "integer"
                },
                "longTermDebt": {
                    "type": "integer"
                },
                "longTermDebtNoncurrent": {
                    "type": "integer"
                },
                "longTermInvestments": {
                    "type": "integer"
                },
                "otherCurrentAssets": {
                    "type": "integer"
                },
                "otherCurrentLiabilities": {
                    "type": "integer"
                },
                "otherNonCurrentAssets": {
                    "type": "integer"
                },
                "otherNonCurrentLiabilities": {
                    "type": "integer"
                },
                "propertyPlantEquipment": {
                    "type": "integer"
                },
                "reportedCurrency": {
                    "type": "string"
                },
                "retainedEarnings": {
                    "type": "integer"
                },
                "shortLongTermDebtTotal": {
                    "type": "integer"
                },
                "shortTermDebt": {
                    "type": "integer"
                },
                "shortTermInvestments": {
                    "type": "integer"
                },
                "totalAssets": {
                    "type": "integer"
                },
                "totalCurrentAssets": {
                    "type": "integer"
                },
                "totalCurrentLiabilities": {
                    "type": "integer"
                },
                "totalLiabilities": {
                    "type": "integer"
                },
                "totalNonCurrentAssets": {
                    "type": "integer"
                },
                "totalNonCurrentLiabilities": {
                    "type": "integer"
                },
                "totalShareholderEquity": {
                    "type": "integer"
                },
                "treasuryStock": {
                    "type": "integer"
                }
            }
        },
        "models.CashFlowStatementsAnnualReport": {
            "type": "object",
            "properties": {
                "capitalExpenditures": {
                    "type": "integer"
                },
                "cashflowFromFinancing": {
                    "type": "integer"
                },
                "cashflowFromInvestment": {
                    "type": "integer"
                },
                "changeInCashAndCashEquivalents": {
                    "type": "integer"
                },
                "changeInExchangeRate": {
                    "type": "integer"
                },
                "changeInInventory": {
                    "type": "integer"
                },
                "changeInOperatingAssets": {
                    "type": "integer"
                },
                "changeInOperatingLiabilities": {
                    "type": "integer"
                },
                "changeInReceivables": {
                    "type": "integer"
                },
                "depreciationDepletionAndAmortization": {
                    "type": "integer"
                },
                "dividendPayout": {
                    "type": "integer"
                },
                "dividendPayoutCommonStock": {
                    "type": "integer"
                },
                "dividendPayoutPreferredStock": {
                    "type": "integer"
                },
                "fiscalDateEnding": {
                    "type": "string"
                },
                "netIncome": {
                    "type": "integer"
                },
                "operatingCashflow": {
                    "type": "integer"
                },
                "paymentsForOperatingActivities": {
                    "type": "integer"
                },
                "paymentsForRepurchaseOfCommonStock": {
                    "type": "integer"
                },
                "paymentsForRepurchaseOfEquity": {
                    "type": "integer"
                },
                "paymentsForRepurchaseOfPreferredStock": {
                    "type": "integer"
                },
                "proceedsFromIssuanceOfCommonStock": {
                    "type": "integer"
                },
                "proceedsFromIssuanceOfLongTermDebtAndCapitalSecuritiesNet": {
                    "type": "integer"
                },
                "proceedsFromIssuanceOfPreferredStock": {
                    "type": "integer"
                },
                "proceedsFromOperatingActivities": {
                    "type": "integer"
                },
                "proceedsFromRepaymentsOfShortTermDebt": {
                    "type": "integer"
                },
                "proceedsFromRepurchaseOfEquity": {
                    "type": "integer"
                },
                "proceedsFromSaleOfTreasuryStock": {
                    "type": "integer"
                },
                "profitLoss": {
                    "type": "integer"
                },
                "reportedCurrency": {
                    "type": "string"
                }
            }
        },
        "models.Company": {
            "type": "object",
            "properties": {
                "country": {
                    "type": "string"
                },
                "currency": {
                    "type": "string"
                },
                "exchange": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "industry": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "sector": {
                    "type": "string"
                },
                "symbol": {
                    "type": "string"
                }
            }
        },
        "models.CompanyAnalysis": {
            "type": "object",
            "properties": {
                "calculated_ratios": {
                    "description": "Ratios calculés",
                    "allOf": [
                        {
                            "$ref": "#/definitions/models.FinancialRatios"
                        }
                    ]
                },
                "company": {
                    "$ref": "#/definitions/models.Company"
                },
                "growth_metrics": {
                    "description": "Métriques dérivées",
                    "allOf": [
                        {
                            "$ref": "#/definitions/models.GrowthMetrics"
                        }
                    ]
                },
                "latest_balance": {
                    "$ref": "#/definitions/models.BalanceSheetAnnualReport"
                },
                "latest_cash_flow": {
                    "$ref": "#/definitions/models.CashFlowStatementsAnnualReport"
                },
                "latest_income": {
                    "$ref": "#/definitions/models.AnnualReportIncomeStatements"
                },
                "overview": {
                    "$ref": "#/definitions/models.CompanyOverview"
                }
            }
        },
        "models.CompanyOverview": {
            "type": "object",
            "properties": {
                "200DayMovingAverage": {
                    "type": "string",
                    "example": "0"
                },
                "50DayMovingAverage": {
                    "type": "string",
                    "example": "0"
                },
                "52WeekHigh": {
                    "type": "string",
                    "example": "0"
                },
                "52WeekLow": {
                    "type": "string",
                    "example": "0"
                },
                "Address": {
                    "type": "string"
                },
                "AnalystTargetPrice": {
                    "type": "string",
                    "example": "0"
                },
                "AssetType": {
                    "type": "string"
                },
                "Beta": {
                    "type": "string",
                    "example": "0"
                },
                "BookValue": {
                    "type": "string",
                    "example": "0"
                },
                "CIK": {
                    "type": "string"
                },
                "Country": {
                    "type": "string"
                },
                "Currency": {
                    "type": "string"
                },
                "Description": {
                    "type": "string"
                },
                "DilutedEPSTTM": {
                    "type": "string",
                    "example": "0"
                },
                "DividendDate": {
                    "description": "\"2023-06-10\"",
                    "type": "string"
                },
                "DividendPerShare": {
                    "type": "string",
                    "example": "0"
                },
                "DividendYield": {
                    "type": "string",
                    "example": "0"
                },
                "EBITDA": {
                    "type": "string",
                    "example": "0"
                },
                "EPS": {
                    "type": "string",
                    "example": "0"
                },
                "EVToEBITDA": {
                    "type": "string",
                    "example": "0"
                },
                "EVToRevenue": {
                    "type": "string",
                    "example": "0"
                },
                "ExDividendDate": {
                    "description": "\"2023-05-09\"",
                    "type": "string"
                },
                "Exchange": {
                    "type": "string"
                },
                "FiscalYearEnd": {
                    "type": "string"
                },
                "ForwardPE": {
                    "type": "string",
                    "example": "0"
                },
                "GrossProfitTTM": {
                    "type": "string",
                    "example": "0"
                },
                "Industry": {
                    "type": "string"
                },
                "LatestQuarter": {
                    "description": "\"2023-03-31\"",
                    "type": "string"
                },
                "MarketCapitalization": {
                    "type": "string",
                    "example": "0"
                },
                "Name": {
                    "type": "string"
                },
                "OperatingMarginTTM": {
                    "type": "string",
                    "example": "0"
                },
                "PEGRatio": {
                    "type": "string",
                    "example": "0"
                },
                "PERatio": {
                    "type": "string",
                    "example": "0"
                },
                "PriceToBookRatio": {
                    "type": "string",
                    "example": "0"
                },
                "PriceToSalesRatioTTM": {
                    "type": "string",
                    "example": "0"
                },
                "ProfitMargin": {
                    "type": "string",
                    "example": "0"
                },
                "QuarterlyEarningsGrowthYOY": {
                    "type": "string",
                    "example": "0"
                },
                "QuarterlyRevenueGrowthYOY": {
                    "type": "string",
                    "example": "0"
                },
                "ReturnOnAssetsTTM": {
                    "type": "string",
                    "example": "0"
                },
                "ReturnOnEquityTTM": {
                    "type": "string",
                    "example": "0"
                },
                "RevenuePerShareTTM": {
                    "type": "string",
                    "example": "0"
                },
                "RevenueTTM": {
                    "type": "string",
                    "example": "0"
                },
                "Sector": {
                    "type": "string"
                },
                "SharesOutstanding": {
                    "type": "string",
                    "example": "0"
                },
                "Symbol": {
                    "type": "string"
                },
                "TrailingPE": {
                    "type": "string",
                    "example": "0"
                }
            }
        },
        "models.FairValue": {
            "type": "object",
            "properties": {
                "estimated_value": {
                    "type": "number"
                },
                "method": {
                    "type": "string"
                },
                "upside": {
                    "type": "number"
                }
            }
        },
        "models.FinancialRatios": {
            "type": "object",
            "properties": {
                "asset_turnover": {
                    "type": "number"
                },
                "debt_to_assets": {
                    "type": "number"
                },
                "debt_to_equity": {
                    "type": "number"
                },
                "earnings_growth_yoy": {
                    "type": "number"
                },
                "fiscal_date": {
                    "type": "string"
                },
                "gross_margin": {
                    "type": "number"
                },
                "inventory_turnover": {
                    "type": "number"
                },
                "net_margin": {
                    "type": "number"
                },
                "operating_margin": {
                    "type": "number"
                },
                "pb_ratio": {
                    "type": "number"
                },
                "pe_ratio": {
                    "type": "number"
                },
                "price_to_sales_ratio": {
                    "type": "number"
                },
                "revenue_growth_yoy": {
                    "type": "number"
                }
            }
        },
        "models.GrowthMetrics": {
            "type": "object",
            "properties": {
                "earnings_growth_1y": {
                    "type": "number"
                },
                "earnings_growth_3y": {
                    "type": "number"
                },
                "revenue_growth_1y": {
                    "type": "number"
                },
                "revenue_growth_3y": {
                    "type": "number"
                }
            }
        },
        "models.HistoricalRatios": {
            "type": "object",
            "properties": {
                "fiscal_date": {
                    "type": "string"
                },
                "ratios": {
                    "$ref": "#/definitions/models.ValuationRatios"
                }
            }
        },
        "models.ScreeningResult": {
            "type": "object",
            "properties": {
                "beta": {
                    "type": "number"
                },
                "company_id": {
                    "type": "integer"
                },
                "industry": {
                    "type": "string"
                },
                "market_cap": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "pb_ratio": {
                    "type": "number"
                },
                "pe_ratio": {
                    "type": "number"
                },
                "price_to_sales": {
                    "type": "number"
                },
                "profit_margin": {
                    "type": "number"
                },
                "roa": {
                    "type": "number"
                },
                "roe": {
                    "type": "number"
                },
                "score": {
                    "description": "Score calculé basé sur les critères",
                    "type": "number"
                },
                "sector": {
                    "type": "string"
                },
                "symbol": {
                    "type": "string"
                }
            }
        },
        "models.ValuationAnalysis": {
            "type": "object",
            "properties": {
                "current_ratios": {
                    "$ref": "#/definitions/models.ValuationRatios"
                },
                "fair_value": {
                    "$ref": "#/definitions/models.FairValue"
                },
                "historical_ratios": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.HistoricalRatios"
                    }
                },
                "symbol": {
                    "type": "string"
                }
            }
        },
        "models.ValuationRatios": {
            "type": "object",
            "properties": {
                "enterprise_value_ebit": {
                    "type": "number"
                },
                "pb_ratio": {
                    "type": "number"
                },
                "pe_ratio": {
                    "type": "number"
                },
                "price_to_cash_flow": {
                    "type": "number"
                },
                "price_to_sales": {
                    "type": "number"
                }
            }
        },
        "pkg.CompanyAnalysisResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "description": "Analyse complète de l'entreprise",
                    "allOf": [
                        {
                            "$ref": "#/definitions/models.CompanyAnalysis"
                        }
                    ]
                },
                "status": {
                    "description": "Statut de la réponse",
                    "type": "string"
                }
            }
        },
        "pkg.ErrorResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "Code d'erreur HTTP",
                    "type": "integer"
                },
                "message": {
                    "description": "Message d'erreur",
                    "type": "string"
                },
                "status": {
                    "description": "Statut de la réponse, e.g., \"error\"",
                    "type": "string"
                }
            }
        },
        "pkg.ScreeningResponse": {
            "type": "object",
            "properties": {
                "count": {
                    "description": "Nombre de résultats",
                    "type": "integer"
                },
                "data": {
                    "description": "Résultats du screening",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.ScreeningResult"
                    }
                },
                "status": {
                    "description": "Statut de la réponse",
                    "type": "string"
                }
            }
        },
        "pkg.ScreeningTemplate": {
            "type": "object",
            "properties": {
                "criteria": {
                    "description": "Critères du template"
                },
                "description": {
                    "description": "Description",
                    "type": "string"
                },
                "name": {
                    "description": "Nom du template",
                    "type": "string"
                }
            }
        },
        "pkg.ScreeningTemplatesResponse": {
            "type": "object",
            "properties": {
                "status": {
                    "description": "Statut de la réponse",
                    "type": "string"
                },
                "templates": {
                    "description": "Liste des templates",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/pkg.ScreeningTemplate"
                    }
                }
            }
        },
        "pkg.SuccessResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "description": "Message de succès",
                    "type": "string"
                },
                "status": {
                    "description": "Statut de la réponse",
                    "type": "string"
                }
            }
        },
        "pkg.ValuationAnalysisResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "description": "Analyse de valorisation",
                    "allOf": [
                        {
                            "$ref": "#/definitions/models.ValuationAnalysis"
                        }
                    ]
                },
                "status": {
                    "description": "Statut de la réponse",
                    "type": "string"
                }
            }
        },
        "services.ScreeningCriteria": {
            "type": "object",
            "properties": {
                "limit": {
                    "description": "Limit results",
                    "type": "integer"
                },
                "max_debt_to_equity": {
                    "description": "Financial health",
                    "type": "number"
                },
                "max_market_cap": {
                    "type": "integer"
                },
                "max_pb_ratio": {
                    "type": "number"
                },
                "max_pe_ratio": {
                    "type": "number"
                },
                "min_current_ratio": {
                    "type": "number"
                },
                "min_eps_growth": {
                    "type": "number"
                },
                "min_market_cap": {
                    "description": "Size",
                    "type": "integer"
                },
                "min_pb_ratio": {
                    "type": "number"
                },
                "min_pe_ratio": {
                    "description": "Valuation ratios",
                    "type": "number"
                },
                "min_price_to_sales": {
                    "type": "number"
                },
                "min_profit_margin": {
                    "type": "number"
                },
                "min_revenue_growth": {
                    "description": "Growth",
                    "type": "number"
                },
                "min_roa": {
                    "type": "number"
                },
                "min_roe": {
                    "description": "Profitability",
                    "type": "number"
                },
                "sectors": {
                    "description": "Sectors (optionnel)",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "My Investment API",
	Description:      "API for analyzing company financials based on Alpha Vantage data.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
